insert into regizori(nume,prenume,data_nasterii) values ('Nolan', 'Christopher', '30-JUN-1970');
insert into regizori(nume,prenume,data_nasterii) values ('Jackson', 'Peter', '31-OCT-1961');
insert into regizori(nume,prenume,data_nasterii) values ('Scott', 'Ridley', '30-NOV-1937');
insert into regizori(nume,prenume,data_nasterii) values ('Coen', 'Joel', '29-NOV-1954');
insert into regizori(nume,prenume,data_nasterii) values ('Scorsese', 'Martin', '17-NOV-1942');
insert into regizori(nume,prenume,data_nasterii) values ('Tarantino', 'Quentin', '27-MAR-1963');
insert into regizori(nume,prenume,data_nasterii) values ('Docter', 'Pete', '9-OCT-1968'); 
insert into regizori(nume,prenume,data_nasterii) values ('Campbell', 'Martin', '24-OCT-1943');
insert into regizori(nume,prenume,data_nasterii) values ('Reeves', 'Matt', '27-APR-1966');
insert into regizori(nume,prenume,data_nasterii) values ('Johnson', 'Rian', '27-DEC-1973');
insert into regizori(nume,prenume,data_nasterii) values ('Luhrmann', 'Baz', '17-SEP-1962');
insert into regizori(nume,prenume,data_nasterii) values ('Autant-Lara', 'Claude', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Burton', 'Tim', '25-AUG-1958');
insert into regizori(nume,prenume,data_nasterii) values ('Verbinski', 'Gore', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Nee', 'Aaron', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Wiley', 'Ethan', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Columbus', 'Chris', '10-SEP-1958');
insert into regizori(nume,prenume,data_nasterii) values ('Zucker', 'ChrisDavid', '16-OCT-1947');
insert into regizori(nume,prenume,data_nasterii) values ('Tiddes', 'Michael', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Singer', 'Bryan', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Gabriadze', 'Levan', NULL);
insert into regizori(nume,prenume,data_nasterii) values ('Mancini', 'Don', NULL);
select * from regizori;

insert into actori(nume,prenume,data_nasterii) values ('Bale', 'Christian', '30-JAN-1974');
insert into actori(nume,prenume,data_nasterii) values ('Wood', 'Elijah', '28-JAN-1981');
insert into actori(nume,prenume,data_nasterii) values ('Crowe', 'Russell', '07-APR-1964');
insert into actori(nume,prenume,data_nasterii) values ('Bardem', 'Javier', '01-MAR-1969');
insert into actori(nume,prenume,data_nasterii) values ('Farmiga', 'Vera', '06-AUG-1973');
insert into actori(nume,prenume,data_nasterii) values ('Waltz', 'Christoph', '04-OCT-1956');
insert into actori(nume,prenume,data_nasterii) values ('Asner', 'Ed', '15-NOV-1929');
insert into actori(nume,prenume,data_nasterii) values ('Pearce', 'Guy', '05-OCT-1967'); 
insert into actori(nume,prenume,data_nasterii) values ('Thurman', 'Uma', '29-APR-1970');
insert into actori(nume,prenume,data_nasterii) values ('Craig', 'Daniel', '02-MAR-1968');
insert into actori(nume,prenume,data_nasterii) values ('Pattinson', 'Robert', '13-MAY-1986');
insert into actori(nume,prenume,data_nasterii) values ('Cline', 'Madelyn', '21-DEC-1997');
insert into actori(nume,prenume,data_nasterii) values ('Butler', 'Austin', '17-AUG-1991');
insert into actori(nume,prenume,data_nasterii) values ('Poehler', 'Amy', '16-SEP-1971');
insert into actori(nume,prenume,data_nasterii) values ('Depp', 'Johnny', '09-JUN-1963');
insert into actori(nume,prenume,data_nasterii) values ('Radcliffe', 'Daniel', '23-JUL-1989');
insert into actori(nume,prenume,data_nasterii) values ('Jackson', 'Sasha', NULL);
insert into actori(nume,prenume,data_nasterii) values ('Wayans', 'Marlon', NULL);
insert into actori(nume,prenume,data_nasterii) values ('Malek', 'Rami', '12-MAY-1981');
insert into actori(nume,prenume,data_nasterii) values ('Hennig', 'Shelley', NULL);
insert into actori(nume,prenume,data_nasterii) values ('Dourif', 'Fiona', NULL);
select * from actori;

insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('The Dark Knight', 2008, 'SuperHero', 1, 1, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('The Lord of The Rings: The Return of The King', 2003, 'Fantasy', 2, 2, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Gladiator', 2000, 'Action', 3, 3, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('No Country For Old Man', 2007, 'Thriller', 4, 4, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('The Departed', 2006, 'Thriller', 5, 5, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Inglorious Basterds', 2009, 'Action', 6, 6, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Up', 2009, 'Animated', 7, 7, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Memento', 2000, 'Mystery', 8, 1, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Kill Bill: Volume One', 2003, 'Action', 9, 6, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Casino Royale', 2006, 'Action', 10, 8, 1);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('The Batman', 2022, 'SuperHero', 11, 9, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Glass Onion: A Knives Out Mystery', 2022, 'Mystery', 12, 10, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Elvis', 2022, 'Musical', 13, 11, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Inside Out', 2015, 'Animated', 14, 7, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Le Comte de Monte-Cristo', 2002, 'Romance', 8, 12, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Charlie and the Chocolate Factory', 2005, 'Fantasy', 15, 13, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'Adventure', 15, 14, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Edward Scissorhands', 1991, 'Drama', 15, 13, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('The Lost City', 2022, 'Romance', 16, 15, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Journey to the Forbidden Valley', 2015, 'Adventure', 17, 16, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Harry Potter and the Sorcerer s Stone', 2001, 'Fantasy', 16, 17, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Scary Movie', 2000, 'Comedy', 18, 18, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Naked', 2017, 'Comedy', 18, 19, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Bohemian Rhapsody', 2018, 'Musical', 19, 20, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Unfriended', 2014, 'Horror', 20, 21, 0);
insert into filme(titlu, an_aparitie, gen, actori_id_actor, regizori_id_regizor, isTop) values ('Curse of Chucky', 2013, 'Horror', 21, 22, 0);

select * from filme;